//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbSettings
// {
//
//   float gBaseColor;                  // Offset:    0 Size:     4
//   float gLuminanceThreshold;         // Offset:    4 Size:     4
//   float gLuminanceStrength;          // Offset:    8 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gInput                            texture  float4          2d             t0      1 
// gOutput                               UAV  float4          2d             u0      1 
// cbSettings                        cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_input vThreadID.xy
dcl_temps 2
dcl_thread_group 16, 16, 1
mov r0.xy, vThreadID.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyzw, t0.xyzw
dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
mov r1.x, cb0[0].x
mov r1.w, l(0)
store_uav_typed u0.xyzw, vThreadID.xyyy, r1.xxxw
lt r0.w, cb0[0].y, r0.w
if_nz r0.w
  mul r0.xyz, r0.xyzx, cb0[0].zzzz
  mov r0.w, l(0)
  store_uav_typed u0.xyzw, vThreadID.xyyy, r0.xyzw
endif 
ret 
// Approximately 14 instruction slots used
