//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 gWorld;                   // Offset:    0 Size:    64
//   float4x4 gTexTransform;            // Offset:   64 Size:    64 [unused]
//   uint gMaterialIndex;               // Offset:  128 Size:     4 [unused]
//   uint gObjPad0;                     // Offset:  132 Size:     4 [unused]
//   uint gObjPad1;                     // Offset:  136 Size:     4 [unused]
//   uint gObjPad2;                     // Offset:  140 Size:     4 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosWS;                  // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  448
//       float FalloffStart;            // Offset:  460
//       float3 Direction;              // Offset:  464
//       float FalloffEnd;              // Offset:  476
//       float3 Position;               // Offset:  480
//       float SpotPower;               // Offset:  492
//
//   } gLights[16];                     // Offset:  448 Size:   768 [unused]
//   float4x4 gShadowView;              // Offset: 1216 Size:    64 [unused]
//   float gMaxBorderPadding;           // Offset: 1280 Size:     4 [unused]
//   float gMinBorderPadding;           // Offset: 1284 Size:     4 [unused]
//   float gCascadeBlendArea;           // Offset: 1288 Size:     4 [unused]
//   float cbPerObjectPad0;             // Offset: 1292 Size:     4 [unused]
//   float4 gShadowBias;                // Offset: 1296 Size:    16 [unused]
//   float4 gShadowTexScale[3];         // Offset: 1312 Size:    48 [unused]
//   float4 gShadowTexOffset[3];        // Offset: 1360 Size:    48 [unused]
//   int gPCFBlurForLoopStart;          // Offset: 1408 Size:     4 [unused]
//   int gPCFBlurForLoopEnd;            // Offset: 1412 Size:     4 [unused]
//   int cbPerObjectPad2;               // Offset: 1416 Size:     4 [unused]
//   int cbPerObjectPad3;               // Offset: 1420 Size:     4 [unused]
//   bool gVisualCascade;               // Offset: 1424 Size:     4 [unused]
//   bool gBlendCascade;                // Offset: 1428 Size:     4 [unused]
//   bool cbPerObjectPad5;              // Offset: 1432 Size:     4 [unused]
//   bool cbPerObjectPad6;              // Offset: 1436 Size:     4 [unused]
//   float4 gCascadeFrustumsEyeSpaceDepthsFloat;// Offset: 1440 Size:    16 [unused]
//   float4 gCascadeFrustumsEyeSpaceDepthsFloat4[3];// Offset: 1456 Size:    48 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// cbPerObject                       cbuffer      NA          NA     CB0            cb0      1 
// cbPass                            cbuffer      NA          NA     CB1            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float       
// TEXCOORD                 0   xy          2     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
//
vs_5_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[0:0][4], immediateIndexed, space=0
dcl_constantbuffer CB1[1:1][25], immediateIndexed, space=0
dcl_input v0.xyz
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_temps 2
mov r0.xyz, v0.xyzx
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, CB0[0][0].xyzw
dp4 r1.y, r0.xyzw, CB0[0][1].xyzw
dp4 r1.z, r0.xyzw, CB0[0][2].xyzw
dp4 r0.w, r0.xyzw, CB0[0][3].xyzw
add r0.xyz, r1.xyzx, CB1[1][24].xyzx
dp4 r1.x, r0.xyzw, CB1[1][16].xyzw
dp4 r1.y, r0.xyzw, CB1[1][17].xyzw
dp4 r1.z, r0.xyzw, CB1[1][19].xyzw
mov o0.xyzw, r1.xyzz
mov o1.xyz, v0.xyzx
ret 
// Approximately 13 instruction slots used
